"""지수

Revision ID: 2518833f9e04
Revises: 7c6972b9ea2b
Create Date: 2025-12-03 11:43:18.257942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2518833f9e04"
down_revision: Union[str, Sequence[str], None] = "7c6972b9ea2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("index", sa.Column("symbol", sa.String(), nullable=False))
    op.create_unique_constraint(None, "index", ["symbol"])
    op.add_column("index_value", sa.Column("change_percent", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("index_value", "change_percent")
    op.drop_constraint(None, "index", type_="unique")
    op.drop_column("index", "symbol")
    # ### end Alembic commands ###
