"""E

Revision ID: 285e2b916d2a
Revises: 393de0404706
Create Date: 2025-12-01 15:39:49.252025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "285e2b916d2a"
down_revision: Union[str, Sequence[str], None] = "393de0404706"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_reviews", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "stock_reviews", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_reviews", type_="foreignkey")
    op.drop_column("stock_reviews", "user_id")
    # ### end Alembic commands ###
