"""w

Revision ID: 3c958de34b44
Revises: 96ae5cf5a690
Create Date: 2025-12-02 15:52:32.883496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c958de34b44'
down_revision: Union[str, Sequence[str], None] = '96ae5cf5a690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_symbol'), table_name='index')
    op.drop_column('index', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_index_symbol'), 'index', ['symbol'], unique=True)
    # ### end Alembic commands ###
