"""add user tables

Revision ID: 6a0b65139e74
Revises: f4e5febc8836
Create Date: 2025-11-27 18:32:57.913066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a0b65139e74"
down_revision: Union[str, Sequence[str], None] = "f4e5febc8836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_index_id"), "index", ["id"], unique=False)
    op.create_index(op.f("ix_index_name"), "index", ["name"], unique=True)
    op.create_table(
        "fraud_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("price_change", sa.Float(), nullable=True),
        sa.Column("volume_change", sa.Float(), nullable=True),
        sa.Column("average_price", sa.Float(), nullable=True),
        sa.Column("average_volume", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "index_component",
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["index.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("index_id", "stock_id"),
    )
    op.create_table(
        "index_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["index.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_index_value_id"), "index_value", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_index_value_id"), table_name="index_value")
    op.drop_table("index_value")
    op.drop_table("index_component")
    op.drop_table("fraud_logs")
    op.drop_index(op.f("ix_index_name"), table_name="index")
    op.drop_index(op.f("ix_index_id"), table_name="index")
    op.drop_table("index")
    # ### end Alembic commands ###
