"""create exchange_rate_history table

Revision ID: 6b2ab84eebf1
Revises: 1ebae82857cd
Create Date: 2025-12-02 16:35:18.749003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b2ab84eebf1'
down_revision: Union[str, Sequence[str], None] = '1ebae82857cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('target_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey'))
    )
    # ### end Alembic commands ###
