"""감정분석 모델 추가

Revision ID: 8e079d518631
Revises: cb3003c9c941
Create Date: 2025-12-17 13:32:07.627027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e079d518631'
down_revision: Union[str, Sequence[str], None] = 'cb3003c9c941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_sentiments', sa.Column('news_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_social_sentiments_news_id'), 'social_sentiments', ['news_id'], unique=False)
    op.create_foreign_key(None, 'social_sentiments', 'news', ['news_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_sentiments', type_='foreignkey')
    op.drop_index(op.f('ix_social_sentiments_news_id'), table_name='social_sentiments')
    op.drop_column('social_sentiments', 'news_id')
    # ### end Alembic commands ###
