"""지수

Revision ID: 96ae5cf5a690
Revises: 285e2b916d2a
Create Date: 2025-12-02 15:08:59.725006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96ae5cf5a690"
down_revision: Union[str, Sequence[str], None] = "285e2b916d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("index", sa.Column("symbol", sa.String(), nullable=True))
    op.add_column("index", sa.Column("current_value", sa.Float(), nullable=True))
    op.add_column("index", sa.Column("change", sa.Float(), nullable=True))
    op.create_index(op.f("ix_index_symbol"), "index", ["symbol"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_index_symbol"), table_name="index")
    op.drop_column("index", "change")
    op.drop_column("index", "current_value")
    op.drop_column("index", "symbol")
    # ### end Alembic commands ###
