"""mbti

Revision ID: ae38e1900147
Revises: 2518833f9e04
Create Date: 2025-12-04 13:19:11.355047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae38e1900147'
down_revision: Union[str, Sequence[str], None] = '2518833f9e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('mbti_type', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('user_mbti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('E', sa.Integer(), nullable=True),
    sa.Column('I', sa.Integer(), nullable=True),
    sa.Column('S', sa.Integer(), nullable=True),
    sa.Column('N', sa.Integer(), nullable=True),
    sa.Column('T', sa.Integer(), nullable=True),
    sa.Column('F', sa.Integer(), nullable=True),
    sa.Column('J', sa.Integer(), nullable=True),
    sa.Column('P', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mbti_id'), 'user_mbti', ['id'], unique=False)
    op.create_unique_constraint('_user_stock_uc', 'user_wishlist', ['user_id', 'stock_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_stock_uc', 'user_wishlist', type_='unique')
    op.drop_index(op.f('ix_user_mbti_id'), table_name='user_mbti')
    op.drop_table('user_mbti')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
