"""지수테이블

Revision ID: cb3003c9c941
Revises: 2ee80ad684e4
Create Date: 2025-12-09 13:43:54.570248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3003c9c941'
down_revision: Union[str, Sequence[str], None] = '2ee80ad684e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_index_id'), 'index', ['id'], unique=False)
    op.create_index(op.f('ix_index_name'), 'index', ['name'], unique=True)
    op.create_table('index_component',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('index_id', 'stock_id')
    )
    op.create_table('index_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_value_id'), 'index_value', ['id'], unique=False)
    op.drop_index(op.f('ix_"index"_id'), table_name='"index"')
    op.drop_index(op.f('ix_"index"_name'), table_name='"index"')
    op.drop_table('"index"')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('"index"',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('"index"_market_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('"index"_pkey')),
    sa.UniqueConstraint('symbol', name=op.f('"index"_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_"index"_name'), '"index"', ['name'], unique=True)
    op.create_index(op.f('ix_"index"_id'), '"index"', ['id'], unique=False)
    op.drop_index(op.f('ix_index_value_id'), table_name='index_value')
    op.drop_table('index_value')
    op.drop_table('index_component')
    op.drop_index(op.f('ix_index_name'), table_name='index')
    op.drop_index(op.f('ix_index_id'), table_name='index')
    op.drop_table('index')
    # ### end Alembic commands ###
