"""mbti

Revision ID: de50493f4296
Revises: ae38e1900147
Create Date: 2025-12-04 13:45:17.064683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de50493f4296"
down_revision: Union[str, Sequence[str], None] = "ae38e1900147"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mbti_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=10), nullable=False),
        sa.Column("option_a", sa.String(), nullable=False),
        sa.Column("option_b", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mbti_questions_id"), "mbti_questions", ["id"], unique=False
    )
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "mbti_type", sa.VARCHAR(length=1), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.drop_index(op.f("ix_mbti_questions_id"), table_name="mbti_questions")
    op.drop_table("mbti_questions")
    # ### end Alembic commands ###
