"""추가

Revision ID: fd0309619078
Revises: de50493f4296
Create Date: 2025-12-04 13:53:04.644384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0309619078'
down_revision: Union[str, Sequence[str], None] = 'de50493f4296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbti_questions', sa.Column('text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbti_questions', 'text')
    # ### end Alembic commands ###
